; Script generated by Hisabati ERP Builder
; -------------------------------------------

[Setup]
AppId={{C6F6E852-3DFC-4BF0-8089-3B9FBFF476A2}
AppName=Hisabati ERP
AppVersion=1.0.0
AppPublisher=basss
DefaultDirName={autopf}\Hisabati ERP
DefaultGroupName=Hisabati ERP
AllowNoIcons=yes
; The installer will NOT be signed, so SmartScreen will show a warning. 
; This is standard for apps without a paid certificate.
OutputDir=..\..\..\..\
OutputBaseFilename=Hisabati_ERP_Setup
SetupIconFile=c:\my app creator\hisabati_app\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "c:\my app creator\hisabati_app\build\windows\x64\runner\Release\hisabati_app.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "c:\my app creator\hisabati_app\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Hisabati ERP"; Filename: "{app}\hisabati_app.exe"
Name: "{autodesktop}\Hisabati ERP"; Filename: "{app}\hisabati_app.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\hisabati_app.exe"; Description: "{cm:LaunchProgram,Hisabati ERP}"; Flags: nowait postinstall skipifsilent
