name: hisabati_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  audioplayers: ^6.6.0
  record: ^6.2.0
  http: ^1.6.0
  path_provider: ^2.1.5
  file_picker: ^10.3.10
  flutter_tts: ^4.2.5
  lottie: ^3.1.2
  mobile_scanner: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.3
  intl: 0.20.2
  provider: ^6.1.2
  supabase_flutter: ^2.12.2
  sqflite: ^2.4.2
  easy_localization: ^3.0.7
  csv: ^6.0.0
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.2
  fl_chart: ^0.68.0
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  sqflite_common_ffi: ^2.3.3
  excel: ^4.0.5
  flutter_staggered_animations: ^1.0.0
  sqlite3_flutter_libs: ^0.5.24
  device_info_plus: ^11.1.1
  system_info_plus: ^0.0.6
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  google_mlkit_text_recognition: ^0.13.0
  sqflite_common_ffi_web: ^1.0.1+1
  mailer: ^7.1.0
  desktop_webview_auth: ^0.0.16
  flutter_stripe: ^11.0.0
  crypto: ^3.0.7
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  msix: ^3.16.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo icon.PNG"
  web:
    generate: true
    image_path: "assets/image/logo icon.PNG"
  windows:
    generate: true
    image_path: "assets/image/logo icon.PNG"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/translations/
    - .env

msix_config:
  display_name: Hisabati ERP
  publisher_display_name: Hisabati
  identity_name: com.hisabati.erp
  msix_version: 1.0.0.0
  logo_path: assets/image/logo icon.PNG
  capabilities: internetClient, removableStorage
  languages: ar, en
