"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextProps {
  language: Language;
  toggleLanguage: () => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ─── NAV ───
    "nav.features": "Features",
    "nav.solutions": "Solutions",
    "nav.security": "AI Security",
    "nav.affiliate": "Affiliate",
    "nav.pricing": "Pricing",
    "nav.resources": "Resources",
    "nav.contact": "Contact",
    "nav.join": "Start Free Trial",
    "nav.signin": "Sign In",
    "nav.menu": "Menu",

    // ─── HERO ───
    "hero.welcome": "The #1 Offline-First ERP Platform",
    "hero.headline": "Revolutionize Your Accounting. Online, Offline, Anytime.",
    "hero.sub": "The ultimate ERP and Accounting System with Local Edge AI. 200+ industry templates. Complete privacy. Zero monthly fees for core features.",
    "hero.download": "Download for",
    "hero.also": "Also available on:",
    "hero.demo": "Watch Demo",
    "hero.trial": "30-Day Free Trial",
    "hero.stat1": "200+",
    "hero.stat1.label": "Industry Templates",
    "hero.stat2": "50+",
    "hero.stat2.label": "Countries Supported",
    "hero.stat3": "100%",
    "hero.stat3.label": "Offline Capable",
    "hero.stat4": "24/7",
    "hero.stat4.label": "AI Assistant",

    // ─── HOW IT WORKS ───
    "how.badge": "Easy Setup",
    "how.title": "Get Started in Minutes",
    "how.sub": "Set up your powerful accounting system in 3 simple steps.",
    "how.step1.title": "1. Download Securely",
    "how.step1.desc": "Get the native app for Windows, macOS, Android, or iOS. No browser required.",
    "how.step2.title": "2. Create Your Company",
    "how.step2.desc": "Choose your industry template. Your data is instantly encrypted and saved locally.",
    "how.step3.title": "3. Sync (Optional)",
    "how.step3.desc": "Connect multiple devices securely. Share data with your team in real-time.",

    // ─── FEATURES ───
    "features.title": "Everything Your Business Needs",
    "features.sub": "A complete ERP platform with 60+ modules built for speed, privacy, and true global scalability.",
    "features.cat.accounting": "Core Accounting",
    "features.cat.sales": "Sales & Invoicing",
    "features.cat.hr": "HR & Payroll",
    "features.cat.inventory": "Inventory & Warehouse",
    "features.cat.reports": "Reports & Analytics",
    "features.cat.ai": "AI & Security",
    "features.f1.title": "Chart of Accounts",
    "features.f1.desc": "Multi-level hierarchical account tree customizable per industry.",
    "features.f2.title": "Double-Entry Journals",
    "features.f2.desc": "Automatic balanced journal entries with full audit trail.",
    "features.f3.title": "Trial Balance",
    "features.f3.desc": "Real-time trial balance with drill-down to individual transactions.",
    "features.f4.title": "Financial Statements",
    "features.f4.desc": "Income Statement, Balance Sheet, Cash Flow, and Owner's Equity reports.",
    "features.f5.title": "Bank Reconciliation",
    "features.f5.desc": "Match bank statements with system records automatically.",
    "features.f6.title": "Multi-Currency",
    "features.f6.desc": "Support for 150+ currencies with automatic exchange rate updates.",
    "features.f7.title": "Professional Invoicing",
    "features.f7.desc": "Create branded invoices in seconds with custom templates.",
    "features.f8.title": "Point of Sale (POS)",
    "features.f8.desc": "Full-featured POS with barcode scanning, receipts, and cash drawer.",
    "features.f9.title": "Quotations & Orders",
    "features.f9.desc": "Convert quotes to sales orders to invoices seamlessly.",
    "features.f10.title": "Credit & Debit Notes",
    "features.f10.desc": "Handle returns, adjustments, and credit management easily.",
    "features.f11.title": "Payment Tracking",
    "features.f11.desc": "Track payments by cash, cheque, bank transfer, or digital wallet.",
    "features.f12.title": "Recurring Invoices",
    "features.f12.desc": "Auto-generate recurring invoices on schedule.",
    "features.f13.title": "Employee Management",
    "features.f13.desc": "Complete employee profiles with documents, contracts, and history.",
    "features.f14.title": "Payroll Processing",
    "features.f14.desc": "Calculate salaries, deductions, overtime, and end-of-service benefits.",
    "features.f15.title": "Attendance & Leaves",
    "features.f15.desc": "Track attendance, leave balances, and overtime hours.",
    "features.f16.title": "Recruitment",
    "features.f16.desc": "Manage job postings, applications, interviews, and hiring.",
    "features.f17.title": "Multi-Warehouse",
    "features.f17.desc": "Manage inventory across unlimited warehouses and locations.",
    "features.f18.title": "Barcode System",
    "features.f18.desc": "Generate and scan barcodes for instant product lookup.",
    "features.f19.title": "Stock Alerts",
    "features.f19.desc": "Automatic alerts for low stock, expiry dates, and reorder points.",
    "features.f20.title": "Inventory Valuation",
    "features.f20.desc": "FIFO, LIFO, and weighted average cost methods.",
    "features.f21.title": "Smart Dashboard",
    "features.f21.desc": "Real-time KPIs, charts, and financial health score.",
    "features.f22.title": "Tax Reports",
    "features.f22.desc": "Automatic VAT/GST calculation and tax return reports.",
    "features.f23.title": "Custom Reports",
    "features.f23.desc": "Build any report with drag-and-drop report builder.",
    "features.f24.title": "Export to PDF/Excel",
    "features.f24.desc": "Export any report or statement in professional formats.",
    "features.f25.title": "Local Edge AI",
    "features.f25.desc": "AI assistant that works 100% offline on your device.",
    "features.f26.title": "Fraud Detection",
    "features.f26.desc": "AI-powered duplicate invoice and anomaly detection.",
    "features.f27.title": "AES-256 Encryption",
    "features.f27.desc": "Military-grade encryption for all your financial data.",
    "features.f28.title": "Audit Trail",
    "features.f28.desc": "Complete log of every action by every user.",

    // ─── INDUSTRY SOLUTIONS ───
    "solutions.title": "Built for Every Industry",
    "solutions.sub": "200+ industry-specific templates with pre-configured charts of accounts, reports, and workflows.",
    "solutions.retail": "Retail & Shops",
    "solutions.retail.desc": "Supermarkets, clothing, electronics, furniture, and more.",
    "solutions.offices": "Offices & Services",
    "solutions.offices.desc": "Law firms, travel agencies, consultancies, and IT services.",
    "solutions.construction": "Construction",
    "solutions.construction.desc": "Contractors, project-based accounting, progress billing.",
    "solutions.manufacturing": "Manufacturing",
    "solutions.manufacturing.desc": "Factories, production lines, BOM, and cost accounting.",
    "solutions.healthcare": "Healthcare",
    "solutions.healthcare.desc": "Hospitals, clinics, pharmacies, and medical labs.",
    "solutions.hotels": "Hotels & Hospitality",
    "solutions.hotels.desc": "Hotels, serviced apartments, room management.",
    "solutions.logistics": "Logistics & Shipping",
    "solutions.logistics.desc": "Shipping companies, delivery services, fleet management.",
    "solutions.automotive": "Automotive",
    "solutions.automotive.desc": "Car dealerships, workshops, parts trading.",
    "solutions.realestate": "Real Estate",
    "solutions.realestate.desc": "Property management, rentals, sales, and development.",
    "solutions.restaurants": "Restaurants & F&B",
    "solutions.restaurants.desc": "Restaurants, cafes, bakeries, and food delivery.",
    "solutions.pharma": "Pharma & Cosmetics",
    "solutions.pharma.desc": "Pharmacies, drug manufacturing, cosmetics production.",
    "solutions.agriculture": "Agriculture",
    "solutions.agriculture.desc": "Farms, livestock, crop management, and agri-business.",
    "solutions.energy": "Energy & Petroleum",
    "solutions.energy.desc": "Gas stations, oil companies, chemical industries.",
    "solutions.technology": "Technology & IT",
    "solutions.technology.desc": "Software companies, computer trading, robotics.",
    "solutions.education": "Education",
    "solutions.education.desc": "Schools, universities, training institutes.",
    "solutions.jewelry": "Jewelry & Precious Metals",
    "solutions.jewelry.desc": "Gold, silver, diamonds, and luxury goods.",
    "solutions.ecommerce": "E-Commerce",
    "solutions.ecommerce.desc": "Online stores, marketplaces, and delivery platforms.",
    "solutions.textiles": "Textiles & Fashion",
    "solutions.textiles.desc": "Clothing manufacturing, fabric trading, fashion retail.",
    "solutions.cleaning": "Cleaning Services",
    "solutions.cleaning.desc": "Cleaning companies, facility management.",
    "solutions.all": "See All 200+ Industries →",

    // ─── EDGE AI ───
    "security.privacy": "100% Local Privacy",
    "security.title": "Your Data. Your Power. Local AI.",
    "security.desc": "Unlike cloud ERPs, Hisabati's built-in AI Agent runs entirely on your device (Edge AI). All financial automation, data processing, and analysis happen locally. Your private data never leaves your network without your explicit permission.",
    "security.li1": "Zero Cloud Data Mining",
    "security.li2": "Instant AI Responses (No Latency)",
    "security.li3": "Local Encryption AES-256",
    "security.li4": "GDPR & Privacy Compliant",
    "security.blocked": "BLOCKED",

    // ─── DEMO VIDEO ───
    "demo.title": "See Hisabati in Action",
    "demo.sub": "Watch how businesses manage their entire operation from a single platform.",
    "demo.cta": "Start Your Free Trial",

    // ─── MARKETING ───
    "marketing.title": "Scale Fast with Built-in Marketing Tools.",
    "marketing.desc": "Stop paying for expensive third-party email tools. Hisabati includes a native mass-emailing engine capable of sending up to 1,000 professional marketing emails or personalized invoices instantly.",
    "marketing.campaign": "Campaign: Q4 Promos",
    "marketing.recipients": "1,000 Recipients selected",
    "marketing.launch": "Launch Campaign",

    // ─── COMPARISON ───
    "comparison.title": "Why Hisabati Wins",
    "comparison.sub": "See why businesses are switching from legacy Cloud ERPs like QuickBooks and Odoo.",
    "comparison.feat": "Feature",
    "comparison.hisabati": "Hisabati",
    "comparison.cloud": "Cloud ERPs",
    "comparison.row1": "Offline Access",
    "comparison.row2": "Local AI Privacy",
    "comparison.row3": "Zero Monthly Fees (Core)",
    "comparison.row4": "Cross-Platform Sync",
    "comparison.row5": "200+ Industry Templates",
    "comparison.row6": "Built-in Email Marketing",
    "comparison.row7": "Manufacturing & BOM",
    "comparison.row8": "Multi-Currency (150+)",
    "comparison.row9": "HR & Payroll",
    "comparison.row10": "POS System",
    "comparison.row11": "Barcode Generator",
    "comparison.row12": "Audit Trail & Fraud Detection",
    "comparison.row13": "Real Estate Management",
    "comparison.row14": "Local Data Encryption",
    "comparison.row15": "No Internet Required",

    // ─── TESTIMONIALS ───
    "testimonials.title": "Trusted by Businesses Worldwide",
    "testimonials.sub": "See what our customers say about switching to Hisabati.",
    "testimonials.t1.name": "Ahmed Al-Rashid",
    "testimonials.t1.role": "CEO, Gulf Trading LLC",
    "testimonials.t1.text": "Hisabati replaced 3 different software we were using. The offline-first approach is perfect for our warehouses with poor internet.",
    "testimonials.t2.name": "Sarah Johnson",
    "testimonials.t2.role": "CFO, TechStart Inc",
    "testimonials.t2.text": "The AI assistant is incredibly helpful. It generates reports and catches errors that we would have missed. Best investment we made.",
    "testimonials.t3.name": "Dr. Fatima Hassan",
    "testimonials.t3.role": "Director, Al-Shifa Medical Center",
    "testimonials.t3.text": "Finally an ERP that understands healthcare accounting. Patient billing, insurance claims, and inventory all in one place.",
    "testimonials.t4.name": "Mohammed Khalil",
    "testimonials.t4.role": "Owner, Khalil Construction",
    "testimonials.t4.text": "Project-based accounting with progress billing changed how we manage our construction projects. Highly recommended.",

    // ─── AFFILIATE ───
    "affiliate.title": "Partner with Hisabati. Earn Passive Income.",
    "affiliate.desc": "Join our global network of marketers. Promote an application businesses actually need. Generate custom invite links, run paid promotions, and earn generous recurring commissions of up to 30%.",
    "affiliate.btn1": "Become an Affiliate",
    "affiliate.btn2": "Get Invite Link",
    "affiliate.stat1": "30%",
    "affiliate.stat1.label": "Commission Rate",
    "affiliate.stat2": "90 Days",
    "affiliate.stat2.label": "Cookie Duration",
    "affiliate.stat3": "$50",
    "affiliate.stat3.label": "Min. Payout",

    // ─── PRICING ───
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.sub": "Start free. Upgrade when you need more. No hidden fees. Cancel anytime.",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.yearly.save": "Save 20%",
    "pricing.mo": "/mo",
    "pricing.yr": "/yr",
    "pricing.buy": "Start Free Trial",
    "pricing.contact": "Contact Sales",
    "pricing.popular": "Most Popular",
    "pricing.all.include": "All plans include:",
    "pricing.all.f1": "Free customer support",
    "pricing.all.f2": "30-day free trial",
    "pricing.all.f3": "No contract required",
    "pricing.all.f4": "Cancel anytime",

    "pricing.starter": "Starter",
    "pricing.starter.desc": "For freelancers and solopreneurs",
    "pricing.starter.price.mo": "$9",
    "pricing.starter.price.yr": "$86",
    "pricing.starter.f1": "1 User",
    "pricing.starter.f2": "Basic Accounting",
    "pricing.starter.f3": "100 Invoices/month",
    "pricing.starter.f4": "1 Warehouse",
    "pricing.starter.f5": "Email Support",
    "pricing.starter.f6": "1 Device Sync",

    "pricing.business": "Business",
    "pricing.business.desc": "For growing small businesses",
    "pricing.business.price.mo": "$29",
    "pricing.business.price.yr": "$278",
    "pricing.business.f1": "3 Users",
    "pricing.business.f2": "Full Accounting + Inventory",
    "pricing.business.f3": "Unlimited Invoices",
    "pricing.business.f4": "3 Warehouses",
    "pricing.business.f5": "Priority Support",
    "pricing.business.f6": "Multi-Device Sync",
    "pricing.business.f7": "Bank Reconciliation",
    "pricing.business.f8": "Edge AI Basic",

    "pricing.professional": "Professional",
    "pricing.professional.desc": "For established businesses",
    "pricing.professional.price.mo": "$59",
    "pricing.professional.price.yr": "$566",
    "pricing.professional.f1": "10 Users",
    "pricing.professional.f2": "All Modules Included",
    "pricing.professional.f3": "Manufacturing & Projects",
    "pricing.professional.f4": "Unlimited Warehouses",
    "pricing.professional.f5": "HR & Payroll",
    "pricing.professional.f6": "Advanced Edge AI",
    "pricing.professional.f7": "Email Marketing (500/mo)",
    "pricing.professional.f8": "Custom Reports",
    "pricing.professional.f9": "API Access",

    "pricing.enterprise": "Enterprise",
    "pricing.enterprise.desc": "For large organizations",
    "pricing.enterprise.price.mo": "$149",
    "pricing.enterprise.price.yr": "$1,430",
    "pricing.enterprise.f1": "25+ Users",
    "pricing.enterprise.f2": "White-Label Options",
    "pricing.enterprise.f3": "Dedicated Account Manager",
    "pricing.enterprise.f4": "On-Premise Deployment",
    "pricing.enterprise.f5": "Custom Integrations",
    "pricing.enterprise.f6": "24/7 Phone Support",
    "pricing.enterprise.f7": "Email Marketing (Unlimited)",
    "pricing.enterprise.f8": "Multi-Branch Management",
    "pricing.enterprise.f9": "SLA Guarantee",

    // ─── FAQ ───
    "faq.title": "Frequently Asked Questions",
    "faq.q1": "Is my data really stored offline?",
    "faq.a1": "Yes, Hisabati stores 100% of your primary data on your local device using encrypted SQLite. We have zero access to your data. Cloud sync is optional and only activates when you explicitly enable it.",
    "faq.q2": "Can I use it on mobile?",
    "faq.a2": "Absolutely. We have native apps for Android and iOS that sync seamlessly with your desktop application over your local network or cloud.",
    "faq.q3": "Does it support multiple users?",
    "faq.a3": "Yes. Depending on your plan, you can have 1 to 25+ users with role-based permissions. Each user sees only what they're authorized to access.",
    "faq.q4": "How does the free trial work?",
    "faq.a4": "You get full access to all Professional plan features for 30 days, no credit card required. After the trial, you can choose any plan or continue with limited free features.",
    "faq.q5": "Can I migrate from QuickBooks or other software?",
    "faq.a5": "Yes. Hisabati supports importing data from CSV, Excel, and has guided migration tools for QuickBooks, Odoo, and other popular accounting software.",
    "faq.q6": "What industries does Hisabati support?",
    "faq.a6": "Hisabati includes 200+ pre-configured industry templates covering retail, manufacturing, construction, healthcare, hospitality, real estate, logistics, agriculture, and many more.",
    "faq.q7": "Is it available in Arabic?",
    "faq.a7": "Yes! Hisabati is fully bilingual (Arabic/English) with complete RTL support. You can switch languages anytime without losing any data.",
    "faq.q8": "How does the AI assistant work offline?",
    "faq.a8": "Hisabati uses Edge AI technology that runs directly on your device. The AI can analyze data, generate reports, detect anomalies, and answer questions without any internet connection.",
    "faq.q9": "What payment methods do you accept?",
    "faq.a9": "We accept Visa, MasterCard, PayPal, bank transfers, Apple Pay, and regional payment methods. Enterprise customers can also pay by invoice.",
    "faq.q10": "Can I cancel my subscription anytime?",
    "faq.a10": "Yes, there is no contract. You can cancel anytime and your data remains on your local device even after cancellation.",

    // ─── CONTACT ───
    "contact.title": "Get in Touch",
    "contact.sub": "Have questions? Our team is ready to help you get started.",
    "contact.name": "Full Name",
    "contact.email": "Email Address",
    "contact.company": "Company Name",
    "contact.message": "Your Message",
    "contact.send": "Send Message",
    "contact.or": "Or reach us directly:",
    "contact.sales": "Talk to Sales",
    "contact.support": "Customer Support",
    "contact.demo": "Schedule a Demo",

    // ─── FOOTER ───
    "footer.desc": "The ultimate offline-first ERP system. Global standard accounting with local Edge AI privacy. Trusted by businesses in 50+ countries.",
    "footer.product": "Product",
    "footer.link1": "Download Windows",
    "footer.link2": "Download macOS",
    "footer.link3": "Pricing",
    "footer.link4": "Partners",
    "footer.features": "Features",
    "footer.solutions": "Industry Solutions",
    "footer.developer": "Company",
    "footer.sys1": "About Us",
    "footer.sys2": "Privacy Policy",
    "footer.sys3": "Terms of Service",
    "footer.sys4": "bassemsabri@outlook.sa",
    "footer.rights": "© 2026 Hisabati. All rights reserved.",
  },
  ar: {
    // ─── NAV ───
    "nav.features": "المميزات",
    "nav.solutions": "الحلول",
    "nav.security": "أمان الذكاء الاصطناعي",
    "nav.affiliate": "نظام الشركاء",
    "nav.pricing": "الأسعار",
    "nav.resources": "الموارد",
    "nav.contact": "تواصل معنا",
    "nav.join": "ابدأ تجربة مجانية",
    "nav.signin": "تسجيل الدخول",
    "nav.menu": "القائمة",

    // ─── HERO ───
    "hero.welcome": "منصة ERP الأولى عالمياً بدون إنترنت",
    "hero.headline": "أحدث ثورة في حساباتك. متصل، غير متصل، في أي وقت.",
    "hero.sub": "النظام المحاسبي وإدارة الموارد الشامل مع ذكاء اصطناعي محلي. أكثر من 200 قالب صناعي. خصوصية تامة. صفر رسوم شهرية للميزات الأساسية.",
    "hero.download": "تحميل لـ",
    "hero.also": "متاح أيضاً على:",
    "hero.demo": "شاهد العرض",
    "hero.trial": "تجربة مجانية 30 يوم",
    "hero.stat1": "+200",
    "hero.stat1.label": "قالب صناعي",
    "hero.stat2": "+50",
    "hero.stat2.label": "دولة مدعومة",
    "hero.stat3": "100%",
    "hero.stat3.label": "يعمل بدون إنترنت",
    "hero.stat4": "24/7",
    "hero.stat4.label": "مساعد ذكي",

    // ─── HOW IT WORKS ───
    "how.badge": "إعداد سهل",
    "how.title": "ابدأ في دقائق",
    "how.sub": "قم بإعداد نظامك المحاسبي القوي في 3 خطوات بسيطة.",
    "how.step1.title": "1. تحميل آمن",
    "how.step1.desc": "احصل على التطبيق الأصلي لنظام ويندوز أو ماك أو أندرويد أو iOS. بدون متصفح.",
    "how.step2.title": "2. أنشئ شركتك",
    "how.step2.desc": "اختر قالب صناعتك. يتم تشفير بياناتك فوراً وحفظها محلياً.",
    "how.step3.title": "3. المزامنة (اختياري)",
    "how.step3.desc": "اربط أجهزة متعددة بأمان. شارك البيانات مع فريقك في الوقت الفعلي.",

    // ─── FEATURES ───
    "features.title": "كل ما يحتاجه عملك",
    "features.sub": "منصة ERP متكاملة بأكثر من 60 وحدة مصممة للسرعة والخصوصية وقابلية التوسع العالمية.",
    "features.cat.accounting": "المحاسبة الأساسية",
    "features.cat.sales": "المبيعات والفواتير",
    "features.cat.hr": "الموارد البشرية والرواتب",
    "features.cat.inventory": "Inventory & Warehouse",
    "features.cat.reports": "التقارير والتحليلات",
    "features.cat.ai": "الذكاء الاصطناعي والأمان",
    "features.f1.title": "شجرة الحسابات",
    "features.f1.desc": "شجرة حسابات متعددة المستويات قابلة للتخصيص حسب الصناعة.",
    "features.f2.title": "القيود المزدوجة",
    "features.f2.desc": "قيود يومية متوازنة تلقائياً مع سجل تدقيق كامل.",
    "features.f3.title": "ميزان المراجعة",
    "features.f3.desc": "ميزان مراجعة لحظي مع إمكانية التنقل للمعاملات الفردية.",
    "features.f4.title": "القوائم المالية",
    "features.f4.desc": "قائمة الدخل والميزانية العمومية والتدفقات النقدية وحقوق الملكية.",
    "features.f5.title": "التسوية البنكية",
    "features.f5.desc": "مطابقة كشوف البنك مع سجلات النظام تلقائياً.",
    "features.f6.title": "متعدد العملات",
    "features.f6.desc": "دعم أكثر من 150 عملة مع تحديث أسعار الصرف تلقائياً.",
    "features.f7.title": "فواتير احترافية",
    "features.f7.desc": "أنشئ فواتير بهويتك التجارية في ثوانٍ مع قوالب مخصصة.",
    "features.f8.title": "نقاط البيع (POS)",
    "features.f8.desc": "نظام نقاط بيع كامل مع مسح الباركود والإيصالات.",
    "features.f9.title": "عروض الأسعار والطلبات",
    "features.f9.desc": "حوّل العروض إلى أوامر بيع إلى فواتير بسلاسة.",
    "features.f10.title": "إشعارات الخصم والائتمان",
    "features.f10.desc": "إدارة المرتجعات والتعديلات والائتمان بسهولة.",
    "features.f11.title": "تتبع المدفوعات",
    "features.f11.desc": "تتبع المدفوعات نقداً أو بشيك أو تحويل بنكي أو محفظة رقمية.",
    "features.f12.title": "فواتير متكررة",
    "features.f12.desc": "إنشاء فواتير متكررة تلقائياً حسب الجدول.",
    "features.f13.title": "إدارة الموظفين",
    "features.f13.desc": "ملفات موظفين كاملة مع المستندات والعقود والسجل.",
    "features.f14.title": "معالجة الرواتب",
    "features.f14.desc": "حساب الرواتب والخصومات والعمل الإضافي ومكافأة نهاية الخدمة.",
    "features.f15.title": "الحضور والإجازات",
    "features.f15.desc": "تتبع الحضور وأرصدة الإجازات وساعات العمل الإضافي.",
    "features.f16.title": "التوظيف",
    "features.f16.desc": "إدارة الوظائف الشاغرة والطلبات والمقابلات والتعيين.",
    "features.f17.title": "مستودعات متعددة",
    "features.f17.desc": "إدارة المخزون عبر مستودعات ومواقع غير محدودة.",
    "features.f18.title": "نظام الباركود",
    "features.f18.desc": "إنشاء ومسح أكواد الباركود للبحث الفوري عن المنتجات.",
    "features.f19.title": "تنبيهات المخزون",
    "features.f19.desc": "تنبيهات تلقائية لنقص المخزون وتواريخ الانتهاء ونقاط إعادة الطلب.",
    "features.f20.title": "تقييم المخزون",
    "features.f20.desc": "طرق FIFO و LIFO والمتوسط المرجح للتكلفة.",
    "features.f21.title": "لوحة بيانات ذكية",
    "features.f21.desc": "مؤشرات أداء لحظية ورسوم بيانية وتقييم الصحة المالية.",
    "features.f22.title": "تقارير ضريبية",
    "features.f22.desc": "حساب ضريبة القيمة المضافة تلقائياً وتقارير الإقرار الضريبي.",
    "features.f23.title": "تقارير مخصصة",
    "features.f23.desc": "أنشئ أي تقرير بأداة بناء التقارير بالسحب والإفلات.",
    "features.f24.title": "تصدير PDF/Excel",
    "features.f24.desc": "تصدير أي تقرير أو كشف بصيغ احترافية.",
    "features.f25.title": "ذكاء اصطناعي محلي",
    "features.f25.desc": "مساعد ذكي يعمل 100% بدون إنترنت على جهازك.",
    "features.f26.title": "كشف الاحتيال",
    "features.f26.desc": "كشف الفواتير المكررة والشذوذ بالذكاء الاصطناعي.",
    "features.f27.title": "تشفير AES-256",
    "features.f27.desc": "تشفير عسكري لجميع بياناتك المالية.",
    "features.f28.title": "سجل التدقيق",
    "features.f28.desc": "سجل كامل لكل إجراء من كل مستخدم.",

    // ─── INDUSTRY SOLUTIONS ───
    "solutions.title": "مصمم لكل صناعة",
    "solutions.sub": "أكثر من 200 قالب صناعي مع شجرة حسابات وتقارير وسير عمل مُعدة مسبقاً.",
    "solutions.retail": "تجزئة ومحلات",
    "solutions.retail.desc": "سوبرماركت، ملابس، إلكترونيات، أثاث، والمزيد.",
    "solutions.offices": "مكاتب وخدمات",
    "solutions.offices.desc": "محاماة، سفريات، استشارات، وخدمات تقنية.",
    "solutions.construction": "مقاولات",
    "solutions.construction.desc": "مقاولون، محاسبة مشاريع، فوترة تقدمية.",
    "solutions.manufacturing": "تصنيع",
    "solutions.manufacturing.desc": "مصانع، خطوط إنتاج، قوائم المواد، ومحاسبة التكاليف.",
    "solutions.healthcare": "رعاية صحية",
    "solutions.healthcare.desc": "مستشفيات، عيادات، صيدليات، ومختبرات طبية.",
    "solutions.hotels": "فنادق وضيافة",
    "solutions.hotels.desc": "فنادق، شقق فندقية، إدارة الغرف.",
    "solutions.logistics": "لوجستيات وشحن",
    "solutions.logistics.desc": "شركات شحن، خدمات توصيل، إدارة أسطول.",
    "solutions.automotive": "سيارات",
    "solutions.automotive.desc": "وكالات سيارات، ورش، تجارة قطع غيار.",
    "solutions.realestate": "عقارات",
    "solutions.realestate.desc": "إدارة عقارات، إيجارات، بيع، وتطوير.",
    "solutions.restaurants": "مطاعم وأغذية",
    "solutions.restaurants.desc": "مطاعم، مقاهي، مخابز، وتوصيل طعام.",
    "solutions.pharma": "أدوية وتجميل",
    "solutions.pharma.desc": "صيدليات، مصانع أدوية، إنتاج مستحضرات تجميل.",
    "solutions.agriculture": "زراعة",
    "solutions.agriculture.desc": "مزارع، ثروة حيوانية، إدارة محاصيل.",
    "solutions.energy": "طاقة وبترول",
    "solutions.energy.desc": "محطات وقود، شركات نفط، صناعات كيميائية.",
    "solutions.technology": "تقنية ومعلومات",
    "solutions.technology.desc": "شركات برمجيات، تجارة كمبيوتر، روبوتات.",
    "solutions.education": "تعليم",
    "solutions.education.desc": "مدارس، جامعات، معاهد تدريب.",
    "solutions.jewelry": "مجوهرات ومعادن ثمينة",
    "solutions.jewelry.desc": "ذهب، فضة، ألماس، وسلع فاخرة.",
    "solutions.ecommerce": "تجارة إلكترونية",
    "solutions.ecommerce.desc": "متاجر إلكترونية، أسواق، ومنصات توصيل.",
    "solutions.textiles": "أقمشة وأزياء",
    "solutions.textiles.desc": "تصنيع ملابس، تجارة أقمشة، بيع أزياء.",
    "solutions.cleaning": "خدمات تنظيف",
    "solutions.cleaning.desc": "شركات نظافة، إدارة مرافق.",
    "solutions.all": "عرض جميع الصناعات الـ 200+ ←",

    // ─── EDGE AI ───
    "security.privacy": "100% خصوصية محلية",
    "security.title": "بياناتك. قوتك. ذكاء اصطناعي محلي.",
    "security.desc": "على عكس الأنظمة السحابية، المساعد الذكي في حساباتي يعمل بالكامل على جهازك (ذكاء الحافة). جميع الأتمتة المالية والمعالجة والتحليل تتم محلياً. بياناتك الخاصة لا تغادر شبكتك أبداً دون إذنك الصريح.",
    "security.li1": "لا تنقيب سحابي للبيانات",
    "security.li2": "ردود ذكية فورية (بدون تأخير)",
    "security.li3": "تشفير محلي AES-256",
    "security.li4": "متوافق مع GDPR والخصوصية",
    "security.blocked": "محظور",

    // ─── DEMO VIDEO ───
    "demo.title": "شاهد حساباتي قيد العمل",
    "demo.sub": "شاهد كيف تدير الشركات عملياتها بالكامل من منصة واحدة.",
    "demo.cta": "ابدأ تجربتك المجانية",

    // ─── MARKETING ───
    "marketing.title": "انمو بسرعة مع أدوات التسويق المدمجة.",
    "marketing.desc": "توقف عن الدفع لأدوات البريد الخارجية. حساباتي يتضمن محرك بريد إلكتروني جماعي قادر على إرسال ما يصل إلى 1,000 بريد تسويقي احترافي أو فواتير مخصصة فوراً.",
    "marketing.campaign": "حملة: عروض الربع الرابع",
    "marketing.recipients": "تم تحديد 1,000 مستلم",
    "marketing.launch": "إطلاق الحملة",

    // ─── COMPARISON ───
    "comparison.title": "لماذا حساباتي الأفضل",
    "comparison.sub": "اكتشف لماذا تهاجر الشركات من الأنظمة السحابية القديمة مثل كويك بوكس وأودو.",
    "comparison.feat": "الميزة",
    "comparison.hisabati": "حساباتي",
    "comparison.cloud": "الأنظمة السحابية",
    "comparison.row1": "العمل بدون إنترنت",
    "comparison.row2": "خصوصية الذكاء المحلي",
    "comparison.row3": "صفر رسوم شهرية (الأساسي)",
    "comparison.row4": "مزامنة عبر المنصات",
    "comparison.row5": "+200 قالب صناعي",
    "comparison.row6": "تسويق بريد إلكتروني مدمج",
    "comparison.row7": "تصنيع وقوائم مواد",
    "comparison.row8": "متعدد العملات (+150)",
    "comparison.row9": "موارد بشرية ورواتب",
    "comparison.row10": "نقاط بيع",
    "comparison.row11": "مولد باركود",
    "comparison.row12": "سجل تدقيق وكشف احتيال",
    "comparison.row13": "إدارة عقارات",
    "comparison.row14": "تشفير بيانات محلي",
    "comparison.row15": "لا يحتاج إنترنت",

    // ─── TESTIMONIALS ───
    "testimonials.title": "موثوق من شركات حول العالم",
    "testimonials.sub": "شاهد ماذا يقول عملاؤنا عن الانتقال إلى حساباتي.",
    "testimonials.t1.name": "أحمد الراشد",
    "testimonials.t1.role": "مدير عام، شركة الخليج للتجارة",
    "testimonials.t1.text": "حساباتي استبدل 3 برامج مختلفة كنا نستخدمها. نهج العمل بدون إنترنت مثالي لمستودعاتنا ذات الإنترنت الضعيف.",
    "testimonials.t2.name": "سارة جونسون",
    "testimonials.t2.role": "مديرة مالية، TechStart Inc",
    "testimonials.t2.text": "المساعد الذكي مفيد بشكل لا يصدق. يولد التقارير ويلتقط أخطاء كنا سنغفلها. أفضل استثمار قمنا به.",
    "testimonials.t3.name": "د. فاطمة حسن",
    "testimonials.t3.role": "مديرة، مركز الشفاء الطبي",
    "testimonials.t3.text": "أخيراً نظام ERP يفهم محاسبة الرعاية الصحية. فوترة المرضى ومطالبات التأمين والمخزون في مكان واحد.",
    "testimonials.t4.name": "محمد خليل",
    "testimonials.t4.role": "Owner, Khalil Construction",
    "testimonials.t4.text": "Project-based accounting with progress billing changed how we manage our construction projects. Highly recommended.",

    // ─── AFFILIATE ───
    "affiliate.title": "كُن شريكاً مع حساباتي. واربح دخلاً ثابتاً.",
    "affiliate.desc": "انضم إلى شبكتنا العالمية من المسوقين. قم بالترويج لتطبيق تحتاجه الشركات فعلياً. احصل على روابط دعوة مخصصة واربح عمولات متكررة تصل إلى 30%.",
    "affiliate.btn1": "انضم كشريك الآن",
    "affiliate.btn2": "احصل على رابطك",
    "affiliate.stat1": "30%",
    "affiliate.stat1.label": "نسبة العمولة",
    "affiliate.stat2": "90 يوم",
    "affiliate.stat2.label": "مدة الكوكي",
    "affiliate.stat3": "$50",
    "affiliate.stat3.label": "حد أدنى للسحب",

    // ─── PRICING ───
    "pricing.title": "أسعار بسيطة وشفافة",
    "pricing.sub": "ابدأ مجاناً. ارتقِ عند الحاجة. بدون رسوم مخفية. إلغاء في أي وقت.",
    "pricing.monthly": "شهري",
    "pricing.yearly": "سنوي",
    "pricing.yearly.save": "وفّر 20%",
    "pricing.mo": "/شهرياً",
    "pricing.yr": "/سنوياً",
    "pricing.buy": "ابدأ تجربة مجانية",
    "pricing.contact": "تواصل مع المبيعات",
    "pricing.popular": "الأكثر طلباً",
    "pricing.all.include": "جميع الخطط تشمل:",
    "pricing.all.f1": "دعم فني مجاني",
    "pricing.all.f2": "تجربة مجانية 30 يوم",
    "pricing.all.f3": "بدون عقد ملزم",
    "pricing.all.f4": "إلغاء في أي وقت",

    "pricing.starter": "المبتدئ",
    "pricing.starter.desc": "للعاملين المستقلين وأصحاب المشاريع الفردية",
    "pricing.starter.price.mo": "$9",
    "pricing.starter.price.yr": "$86",
    "pricing.starter.f1": "مستخدم واحد",
    "pricing.starter.f2": "محاسبة أساسية",
    "pricing.starter.f3": "100 فاتورة/شهر",
    "pricing.starter.f4": "مستودع واحد",
    "pricing.starter.f5": "دعم عبر البريد",
    "pricing.starter.f6": "مزامنة جهاز واحد",

    "pricing.business": "الأعمال",
    "pricing.business.desc": "للشركات الصغيرة المتنامية",
    "pricing.business.price.mo": "$29",
    "pricing.business.price.yr": "$278",
    "pricing.business.f1": "3 مستخدمين",
    "pricing.business.f2": "محاسبة كاملة + مخزون",
    "pricing.business.f3": "فواتير غير محدودة",
    "pricing.business.f4": "3 مستودعات",
    "pricing.business.f5": "دعم فني أولوية",
    "pricing.business.f6": "مزامنة أجهزة متعددة",
    "pricing.business.f7": "تسوية بنكية",
    "pricing.business.f8": "ذكاء اصطناعي أساسي",

    "pricing.professional": "المحترف",
    "pricing.professional.desc": "للشركات الراسخة",
    "pricing.professional.price.mo": "$59",
    "pricing.professional.price.yr": "$566",
    "pricing.professional.f1": "10 مستخدمين",
    "pricing.professional.f2": "جميع الوحدات مضمنة",
    "pricing.professional.f3": "تصنيع ومشاريع",
    "pricing.professional.f4": "مستودعات غير محدودة",
    "pricing.professional.f5": "موارد بشرية ورواتب",
    "pricing.professional.f6": "ذكاء اصطناعي متقدم",
    "pricing.professional.f7": "تسويق بريد (500/شهر)",
    "pricing.professional.f8": "تقارير مخصصة",
    "pricing.professional.f9": "وصول API",

    "pricing.enterprise": "المؤسسات",
    "pricing.enterprise.desc": "للمنظمات الكبيرة",
    "pricing.enterprise.price.mo": "$149",
    "pricing.enterprise.price.yr": "$1,430",
    "pricing.enterprise.f1": "+25 مستخدم",
    "pricing.enterprise.f2": "خيارات العلامة البيضاء",
    "pricing.enterprise.f3": "مدير حساب مخصص",
    "pricing.enterprise.f4": "استضافة داخلية",
    "pricing.enterprise.f5": "تكامل مخصص",
    "pricing.enterprise.f6": "دعم هاتفي 24/7",
    "pricing.enterprise.f7": "تسويق بريد (غير محدود)",
    "pricing.enterprise.f8": "إدارة فروع متعددة",
    "pricing.enterprise.f9": "ضمان SLA",

    // ─── FAQ ───
    "faq.title": "الأسئلة الشائعة",
    "faq.q1": "هل بياناتي مخزنة حقاً بدون إنترنت؟",
    "faq.a1": "نعم، حساباتي يخزن 100% من بياناتك على جهازك المحلي باستخدام SQLite المشفر. ليس لدينا أي وصول لبياناتك. المزامنة السحابية اختيارية ولا تعمل إلا عند تفعيلها صراحةً.",
    "faq.q2": "هل يمكنني استخدامه على الجوال؟",
    "faq.a2": "بالتأكيد. لدينا تطبيقات أصلية لـ Android و iOS تتزامن بسلاسة مع تطبيق سطح المكتب عبر شبكتك المحلية أو السحابة.",
    "faq.q3": "هل يدعم تعدد المستخدمين؟",
    "faq.a3": "نعم. حسب خطتك، يمكنك إضافة من 1 إلى 25+ مستخدم مع صلاحيات مبنية على الأدوار. كل مستخدم يرى فقط ما هو مخول بالوصول إليه.",
    "faq.q4": "كيف تعمل التجربة المجانية؟",
    "faq.a4": "تحصل على وصول كامل لجميع ميزات خطة المحترف لمدة 30 يوماً، بدون بطاقة ائتمان. بعد التجربة، يمكنك اختيار أي خطة أو الاستمرار بميزات مجانية محدودة.",
    "faq.q5": "هل يمكنني الترحيل من كويك بوكس أو برامج أخرى؟",
    "faq.a5": "نعم. حساباتي يدعم استيراد البيانات من CSV و Excel ولديه أدوات ترحيل موجهة من كويك بوكس وأودو وبرامج المحاسبة الشائعة الأخرى.",
    "faq.q6": "ما الصناعات التي يدعمها حساباتي؟",
    "faq.a6": "حساباتي يتضمن أكثر من 200 قالب صناعي مُعد مسبقاً يغطي التجزئة والتصنيع والمقاولات والرعاية الصحية والضيافة والعقارات واللوجستيات والزراعة وغيرها الكثير.",
    "faq.q7": "هل متاح باللغة العربية؟",
    "faq.a7": "نعم! حساباتي ثنائي اللغة بالكامل (عربي/إنجليزي) مع دعم RTL كامل. يمكنك تبديل اللغة في أي وقت دون فقدان أي بيانات.",
    "faq.q8": "كيف يعمل المساعد الذكي بدون إنترنت؟",
    "faq.a8": "حساباتي يستخدم تقنية Edge AI التي تعمل مباشرة على جهازك. يمكن للذكاء الاصطناعي تحليل البيانات وإنشاء التقارير واكتشاف الشذوذ والإجابة على الأسئلة بدون أي اتصال بالإنترنت.",
    "faq.q9": "ما طرق الدفع المقبولة؟",
    "faq.a9": "نقبل فيزا وماستركارد وباي بال والتحويلات البنكية وApple Pay وطرق الدفع المحلية. عملاء المؤسسات يمكنهم الدفع بفاتورة.",
    "faq.q10": "هل يمكنني إلغاء اشتراكي في أي وقت؟",
    "faq.a10": "نعم، لا يوجد عقد ملزم. يمكنك الإلغاء في أي وقت وتبقى بياناتك على جهازك المحلي حتى بعد الإلغاء.",

    // ─── CONTACT ───
    "contact.title": "تواصل معنا",
    "contact.sub": "هل لديك أسئلة؟ فريقنا جاهز لمساعدتك في البدء.",
    "contact.name": "الاسم الكامل",
    "contact.email": "البريد الإلكتروني",
    "contact.company": "اسم الشركة",
    "contact.message": "رسالتك",
    "contact.send": "إرسال الرسالة",
    "contact.or": "أو تواصل معنا مباشرة:",
    "contact.sales": "تحدث مع المبيعات",
    "contact.support": "دعم العملاء",
    "contact.demo": "احجز عرض توضيحي",

    // ─── FOOTER ───
    "footer.desc": "نظام ERP الشامل الذي يعمل بدون إنترنت أولاً. محاسبة عالمية المعايير مع خصوصية الذكاء الاصطناعي المحلي. موثوق من شركات في أكثر من 50 دولة.",
    "footer.product": "المنتج",
    "footer.link1": "تحميل لنظام ويندوز",
    "footer.link2": "تحميل للماك",
    "footer.link3": "الأسعار",
    "footer.link4": "الشركاء",
    "footer.features": "المميزات",
    "footer.solutions": "الحلول الصناعية",
    "footer.developer": "الشركة",
    "footer.sys1": "من نحن",
    "footer.sys2": "سياسة الخصوصية",
    "footer.sys3": "شروط الخدمة",
    "footer.sys4": "bassemsabri@outlook.sa",
    "footer.rights": "© 2026 حساباتي. جميع الحقوق محفوظة.",
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const timer = setTimeout(() => {
      const saved = localStorage.getItem("hisabati_lang") as Language;
      if (saved && (saved === "en" || saved === "ar")) {
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setLanguage(saved);
      } else {
        const isArabic = navigator.language.startsWith("ar");
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setLanguage(isArabic ? "ar" : "en");
      }
    }, 0);
    return () => clearTimeout(timer);
  }, []);

  const toggleLanguage = () => {
    const newLang = language === "en" ? "ar" : "en";
    setLanguage(newLang);
    localStorage.setItem("hisabati_lang", newLang);
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [dir, language]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, dir, t }}>
      <div dir={dir}>{children}</div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
